In [1]:
# Write a Python function that takes a sequence of numbers and determines whether all the numbers are different from each other

In [6]:

def strlen(str1):
    count = 0
    for char in str1:
        count += 1
    return count

print(strlen("chaitanya"))

9


In [8]:
# Write a Python program to count the number of characters (character frequency) in a string

In [21]:
def charfreq(char1):
    dict = {}
    for n in char1:
        keys = dict.keys()
        if n in keys:
            dict[n] += 1
        else:
            dict[n] = 1
    return dict
print(charfreq("CHAITANYA"))

{'C': 1, 'H': 1, 'A': 3, 'I': 1, 'T': 1, 'N': 1, 'Y': 1}


In [25]:
# Write a Python program to get a string made of the first 2 and the last 2 chars from a given a string.
# If the string length is less than 2, return instead of the empty string.

In [41]:
x = ("my name is chaiatnya singhal")
if len(x) > 2:
    print(x[ :2]+x[-2:])
else:
    print("str should be equal or greater than 2")

myal


                                            OR

In [54]:
def lol(pagal):
    if len(pagal) >= 2:
        print(pagal[ :2]+pagal[-2:])
    else:
        print("str should be equal or greater than 2")
        
lol("jasvdwjdvqwdwvd")

javd


In [102]:
a = input("type: ")

b = a.replace(a[0],"$").replace("$",a[0],1)
print(b)

type: google
goo$le


In [ ]:
# Write a Python program to add 'ing' at the end of a given string (length should be at least 3).
# If the given string already ends with 'ing' then add 'ly' instead. 
# If the string length of the given string is less than 3, leave it unchanged

In [145]:
a= input("type: ")

if len(a) >= 3:
    if "ly" not in a[ -2: ] and "ing" not in a[ -3]: 
        print (a + "ing")
    elif  "ly" in a[ -2: ]:
        print ( a[:-2 ] + "ing" )
    elif "ing" in a[ -3: ]:
        print ( a[:-3 ] + "ly" )
else:
    print("No Change")

type: lol
loling


                                   bit change in question

In [ ]:
s = input("enter: ")
c = str("a,e,i,o,u")

if len(s) >= 3:
    if c in s[-1]:
        print(s[ :-2 ] + "ing" )
else:
    print("no change")

In [15]:
my_dict = {"a": 1, "c":9, "g":8, "j":5}

l = list(my_dict.values())
l.sort()

print(l)

[1, 5, 8, 9]


In [16]:
my_dict = {"a": 1, "c":9, "g":8, "j":5}

l = list(my_dict.values())
l.sort(reverse = True)

print(l)

[9, 8, 5, 1]


In [21]:
 s = {0: 10, 1: 20}
    
s[2] = 30

s

{0: 10, 1: 20, 2: 30}

In [51]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}


d4 = {**dic1, **dic2, **dic3}
d4

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

                                 OR

In [62]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4 = {}

for d in (dic1,dic2,dic3): dic4.update(d)
dic4

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

In [66]:
dic2={3:30, 4:40}
print(dic2.get(50))

None


In [68]:
a = ("b","c")
l = ("g","h")

print(a + l)

('b', 'c', 'g', 'h')


In [76]:
a = ["b","c"]
a.append("n")
a

['b', 'c', 'n']

In [80]:
s = {0: 10, 1: 20}

print(s)

{0: 10, 1: 20}


dict_items([(0, 10), (1, 20)])

levels = int(input("enter: "))

for abc in range(1, levels+1):
    for num in range(abc):
        print(abc,end=" ")
    print("\n")
    
    

In [150]:
a = (4,5,6,7)
arange(1,2)

[4, 7, 5, 4, 7]


In [161]:
levels = (int(input("enter: ")))

for i in range(1, levels+1):
    for x in range(i):
        print(i, end=" ")
    print("\n")
                    

enter: 5
1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



In [22]:
import numpy as np

a = np.random.rand(random.randint(5,10))
a

array([0.60446963, 0.20712386, 0.63055035, 0.13818039, 0.27250796,
       0.37337501, 0.56608534, 0.46065626, 0.82726638])

In [45]:
a = np.linspace(1,45,5,"int")

In [46]:
a

array([ 1., 12., 23., 34., 45.])

In [47]:
a.dtype

dtype('float64')

In [49]:
b =np.arange(1,45,5,"int")

In [50]:
b

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [51]:
b.dtype

dtype('int32')

In [57]:
n1 = np.array([[1,0,2],[4,-2,3]])
n2 = np.array([[4,0],[2,3],[1,0]])

prod = n1.dot(n2)
prod

array([[ 6,  0],
       [15, -6]])

In [54]:
n1

array([[ 1,  0,  2],
       [ 4, -2,  3]])

In [55]:
n2

array([[4, 0, 1],
       [2, 3, 0]])